apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MAX_FILES: "{{ .Values.config.maxFiles }}"
  CACHE_DIR: "{{ .Values.config.cacheDir }}"