{{- $existingSecret := lookup "v1" "Secret" .Values.namespace (printf "%s-secrets" .Release.Name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
{{- if $existingSecret }}
data:
  GITHUB_TOKEN: {{ index $existingSecret.data "GITHUB_TOKEN" | quote }}
  GROQ_API_KEY: {{ index $existingSecret.data "GROQ_API_KEY" | quote }}
  MISTRAL_API_KEY: {{ index $existingSecret.data "MISTRAL_API_KEY" | quote }}
{{- else }}
stringData:
  GITHUB_TOKEN: "{{ .Values.secrets.githubToken }}"
  GROQ_API_KEY: "{{ .Values.secrets.groqApiKey }}"
  MISTRAL_API_KEY: "{{ .Values.secrets.mistralApiKey }}"
{{- end }}
