apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GITHUB_TOKEN: "{{ .Values.secrets.githubToken }}"
  GROQ_API_KEY: "{{ .Values.secrets.groqApiKey }}"
  MISTRAL_API_KEY: "{{ .Values.secrets.mistralApiKey }}"